---
- name: Update and upgrade apt packages
  hosts: all
  remote_user: ngk       # Explicitly specify the remote user
  become: yes            # Enable privilege escalation if necessary
  become_method: sudo    # Specify the method for privilege escalation

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
