---
- name: Update and upgrade apt packages
  hosts: all
  become: yes

  tasks:
    - name: Update packages with apt
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'
      become: yes

    - name: Upgrade packages with apt
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_pkg_mgr == 'apt'
      become: yes
